/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Minicheatsheet4 = {
  _id: string;
  _type: "minicheatsheet4";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageNumber?: number;
  type?: string;
  runningHead?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    listItem?: never;
    markDefs?: Array<{
      className?: string;
      _type: "customClass";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    className?: string;
    _type: "image";
    _key: string;
  } | {
    className?: string;
    html?: string;
    assets?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
      listItem?: never;
      markDefs?: Array<{
        className?: string;
        _type: "customClass";
        _key: string;
      } | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      className?: string;
      _type: "image";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }>;
  answerList?: Array<{
    order?: number;
    answer?: string;
    reason?: string;
    isRight?: boolean;
    _key: string;
  }>;
};

export type Minicheatsheet3 = {
  _id: string;
  _type: "minicheatsheet3";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageNumber?: number;
  type?: string;
  runningHead?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    listItem?: never;
    markDefs?: Array<{
      className?: string;
      _type: "customClass";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    className?: string;
    _type: "image";
    _key: string;
  } | {
    className?: string;
    html?: string;
    assets?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
      listItem?: never;
      markDefs?: Array<{
        className?: string;
        _type: "customClass";
        _key: string;
      } | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      className?: string;
      _type: "image";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }>;
  answerList?: Array<{
    order?: number;
    answer?: string;
    reason?: string;
    isRight?: boolean;
    _key: string;
  }>;
};

export type Minicheatsheet2 = {
  _id: string;
  _type: "minicheatsheet2";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageNumber?: number;
  type?: string;
  runningHead?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    listItem?: never;
    markDefs?: Array<{
      className?: string;
      _type: "customClass";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    className?: string;
    _type: "image";
    _key: string;
  } | {
    className?: string;
    html?: string;
    assets?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
      listItem?: never;
      markDefs?: Array<{
        className?: string;
        _type: "customClass";
        _key: string;
      } | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      className?: string;
      _type: "image";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }>;
  answerList?: Array<{
    order?: number;
    answer?: string;
    reason?: string;
    isRight?: boolean;
    _key: string;
  }>;
};

export type Minicheatsheet1 = {
  _id: string;
  _type: "minicheatsheet1";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageNumber?: number;
  type?: string;
  runningHead?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    listItem?: never;
    markDefs?: Array<{
      className?: string;
      _type: "customClass";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    className?: string;
    _type: "image";
    _key: string;
  } | {
    className?: string;
    html?: string;
    assets?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
      listItem?: never;
      markDefs?: Array<{
        className?: string;
        _type: "customClass";
        _key: string;
      } | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      className?: string;
      _type: "image";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }>;
  answerList?: Array<{
    order?: number;
    answer?: string;
    reason?: string;
    isRight?: boolean;
    _key: string;
  }>;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageNumber?: number;
  type?: string;
  runningHead?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    listItem?: never;
    markDefs?: Array<{
      className?: string;
      _type: "customClass";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    className?: string;
    _type: "image";
    _key: string;
  } | {
    className?: string;
    html?: string;
    assets?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
      listItem?: never;
      markDefs?: Array<{
        className?: string;
        _type: "customClass";
        _key: string;
      } | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      className?: string;
      _type: "image";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }>;
  answerList?: Array<{
    order?: number;
    answer?: string;
    reason?: string;
    isRight?: boolean;
    _key: string;
  }>;
};

export type Signin_page = {
  _id: string;
  _type: "signin_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  image?: {
    file?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    altText?: string;
  };
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  content?: string;
  active?: boolean;
};

export type About_page = {
  _id: string;
  _type: "about_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  description?: string;
  image?: {
    file?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    altText?: string;
  };
};

export type MyLearning = {
  _id: string;
  _type: "myLearning";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  description?: string;
  image?: {
    file?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    altText?: string;
  };
};

export type Thanks_page = {
  _id: string;
  _type: "thanks_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: string;
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Enrollnow_page = {
  _id: string;
  _type: "enrollnow_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  subtitle?: string;
  title?: string;
  description?: string;
  price?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  lists?: Array<{
    order?: number;
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
};

export type Free_signup_form = {
  _id: string;
  _type: "free_signup_form";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subtitle?: string;
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Home_page = {
  _id: string;
  _type: "home_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  type?: string;
  title?: string;
  description?: string;
  image?: {
    file?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    altText?: string;
  };
  lists?: Array<{
    order?: number;
    type?: string;
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | Slug | Minicheatsheet4 | Minicheatsheet3 | Minicheatsheet2 | Minicheatsheet1 | Product | Signin_page | Faq | About_page | MyLearning | Thanks_page | Enrollnow_page | Free_signup_form | Home_page | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "home_page"] | order(order asc){  _id, order, type, title, description, image, lists}
export type HOMEPAGE_QUERYResult = Array<{
  _id: string;
  order: number | null;
  type: string | null;
  title: string | null;
  description: string | null;
  image: {
    file?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    altText?: string;
  } | null;
  lists: Array<{
    order?: number;
    type?: string;
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }> | null;
}>;
// Variable: FREESIGNUPFORM_QUERY
// Query: *[_type == "free_signup_form"]{  _id, subtitle, title, description, image}
export type FREESIGNUPFORM_QUERYResult = Array<{
  _id: string;
  subtitle: string | null;
  title: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: ENROLLNOWPAGE_QUERY
// Query: *[_type == "enrollnow_page"]{  _id, order, subtitle, title, description, price, image, lists}
export type ENROLLNOWPAGE_QUERYResult = Array<{
  _id: string;
  order: number | null;
  subtitle: string | null;
  title: string | null;
  description: string | null;
  price: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  lists: Array<{
    order?: number;
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }> | null;
}>;
// Variable: THANKSPAGE_QUERY
// Query: *[_type == "thanks_page"]{  _id, type, title, description, image}
export type THANKSPAGE_QUERYResult = Array<{
  _id: string;
  type: string | null;
  title: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: MYLEARNINGPAGE_QUERY
// Query: *[_type == "myLearning"] | order(order asc){  _id, order, title, description, image}
export type MYLEARNINGPAGE_QUERYResult = Array<{
  _id: string;
  order: number | null;
  title: string | null;
  description: string | null;
  image: {
    file?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    altText?: string;
  } | null;
}>;
// Variable: ABOUTUSPAGE_QUERY
// Query: *[_type == "about_page"] | order(order asc){  _id, order, title, description, image}
export type ABOUTUSPAGE_QUERYResult = Array<{
  _id: string;
  order: number | null;
  title: string | null;
  description: string | null;
  image: {
    file?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    altText?: string;
  } | null;
}>;
// Variable: SIGNINPAGE_QUERY
// Query: *[_type == "signin_page"]{  _id, title, description, image}
export type SIGNINPAGE_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  image: {
    file?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    altText?: string;
  } | null;
}>;
// Variable: FAQS_QUERY
// Query: *[_type == "faq"] | order(order asc){  _id, order, title, content, active}
export type FAQS_QUERYResult = Array<{
  _id: string;
  order: number | null;
  title: string | null;
  content: string | null;
  active: boolean | null;
}>;
// Variable: PRODUCTS_QUERY
// Query: *[_type == "product"] | order(pageNumber asc){  _id, pageNumber, type, runningHead, body, answerList}
export type PRODUCTS_QUERYResult = Array<{
  _id: string;
  pageNumber: number | null;
  type: string | null;
  runningHead: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: never;
    markDefs?: Array<{
      className?: string;
      _type: "customClass";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    className?: string;
    _type: "image";
    _key: string;
  } | {
    className?: string;
    html?: string;
    assets?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: never;
      markDefs?: Array<{
        className?: string;
        _type: "customClass";
        _key: string;
      } | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      className?: string;
      _type: "image";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }> | null;
  answerList: Array<{
    order?: number;
    answer?: string;
    reason?: string;
    isRight?: boolean;
    _key: string;
  }> | null;
}>;
// Variable: MiniCheatSheet1_QUERY
// Query: *[_type == "minicheatsheet1"] | order(pageNumber asc){  _id, pageNumber, type, runningHead, body, answerList}
export type MiniCheatSheet1_QUERYResult = Array<{
  _id: string;
  pageNumber: number | null;
  type: string | null;
  runningHead: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: never;
    markDefs?: Array<{
      className?: string;
      _type: "customClass";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    className?: string;
    _type: "image";
    _key: string;
  } | {
    className?: string;
    html?: string;
    assets?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: never;
      markDefs?: Array<{
        className?: string;
        _type: "customClass";
        _key: string;
      } | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      className?: string;
      _type: "image";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }> | null;
  answerList: Array<{
    order?: number;
    answer?: string;
    reason?: string;
    isRight?: boolean;
    _key: string;
  }> | null;
}>;
// Variable: MiniCheatSheet2_QUERY
// Query: *[_type == "minicheatsheet2"] | order(pageNumber asc){  _id, pageNumber, type, runningHead, body, answerList}
export type MiniCheatSheet2_QUERYResult = Array<{
  _id: string;
  pageNumber: number | null;
  type: string | null;
  runningHead: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: never;
    markDefs?: Array<{
      className?: string;
      _type: "customClass";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    className?: string;
    _type: "image";
    _key: string;
  } | {
    className?: string;
    html?: string;
    assets?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: never;
      markDefs?: Array<{
        className?: string;
        _type: "customClass";
        _key: string;
      } | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      className?: string;
      _type: "image";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }> | null;
  answerList: Array<{
    order?: number;
    answer?: string;
    reason?: string;
    isRight?: boolean;
    _key: string;
  }> | null;
}>;
// Variable: MiniCheatSheet3_QUERY
// Query: *[_type == "minicheatsheet3"] | order(pageNumber asc){  _id, pageNumber, type, runningHead, body, answerList}
export type MiniCheatSheet3_QUERYResult = Array<{
  _id: string;
  pageNumber: number | null;
  type: string | null;
  runningHead: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: never;
    markDefs?: Array<{
      className?: string;
      _type: "customClass";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    className?: string;
    _type: "image";
    _key: string;
  } | {
    className?: string;
    html?: string;
    assets?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: never;
      markDefs?: Array<{
        className?: string;
        _type: "customClass";
        _key: string;
      } | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      className?: string;
      _type: "image";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }> | null;
  answerList: Array<{
    order?: number;
    answer?: string;
    reason?: string;
    isRight?: boolean;
    _key: string;
  }> | null;
}>;
// Variable: MiniCheatSheet4_QUERY
// Query: *[_type == "minicheatsheet4"] | order(pageNumber asc){  _id, pageNumber, type, runningHead, body, answerList}
export type MiniCheatSheet4_QUERYResult = Array<{
  _id: string;
  pageNumber: number | null;
  type: string | null;
  runningHead: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: never;
    markDefs?: Array<{
      className?: string;
      _type: "customClass";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    className?: string;
    _type: "image";
    _key: string;
  } | {
    className?: string;
    html?: string;
    assets?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: never;
      markDefs?: Array<{
        className?: string;
        _type: "customClass";
        _key: string;
      } | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      className?: string;
      _type: "image";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }> | null;
  answerList: Array<{
    order?: number;
    answer?: string;
    reason?: string;
    isRight?: boolean;
    _key: string;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"home_page\"] | order(order asc){\n  _id, order, type, title, description, image, lists\n}": HOMEPAGE_QUERYResult;
    "*[_type == \"free_signup_form\"]{\n  _id, subtitle, title, description, image\n}": FREESIGNUPFORM_QUERYResult;
    "*[_type == \"enrollnow_page\"]{\n  _id, order, subtitle, title, description, price, image, lists\n}": ENROLLNOWPAGE_QUERYResult;
    "*[_type == \"thanks_page\"]{\n  _id, type, title, description, image\n}": THANKSPAGE_QUERYResult;
    "*[_type == \"myLearning\"] | order(order asc){\n  _id, order, title, description, image\n}": MYLEARNINGPAGE_QUERYResult;
    "*[_type == \"about_page\"] | order(order asc){\n  _id, order, title, description, image\n}": ABOUTUSPAGE_QUERYResult;
    "*[_type == \"signin_page\"]{\n  _id, title, description, image\n}": SIGNINPAGE_QUERYResult;
    "*[_type == \"faq\"] | order(order asc){\n  _id, order, title, content, active\n}": FAQS_QUERYResult;
    "*[_type == \"product\"] | order(pageNumber asc){\n  _id, pageNumber, type, runningHead, body, answerList\n}": PRODUCTS_QUERYResult;
    "*[_type == \"minicheatsheet1\"] | order(pageNumber asc){\n  _id, pageNumber, type, runningHead, body, answerList\n}": MiniCheatSheet1_QUERYResult;
    "*[_type == \"minicheatsheet2\"] | order(pageNumber asc){\n  _id, pageNumber, type, runningHead, body, answerList\n}": MiniCheatSheet2_QUERYResult;
    "*[_type == \"minicheatsheet3\"] | order(pageNumber asc){\n  _id, pageNumber, type, runningHead, body, answerList\n}": MiniCheatSheet3_QUERYResult;
    "*[_type == \"minicheatsheet4\"] | order(pageNumber asc){\n  _id, pageNumber, type, runningHead, body, answerList\n}": MiniCheatSheet4_QUERYResult;
  }
}
